### ISSUE TITLE
Pegasus doesn’t start

### ISSUE THREAD

**Issue by merwok** [flathub/org.pegasus_frontend.Pegasus#1]
Starting the program doesn’t show any window.  Warnings from program output:

```
[w] QQmlApplicationEngine failed to load component
[w] qrc:/frontend/main.qml:-1 File was compiled ahead of time with an incompatible
       version of Qt and the original file cannot be found. Please recompile
```

Note that I don’t know if the program is meant to show windows if no games are found.
I have Steam installed with Flatpak too but Pegasus detects 0 Steam games.
I don’t have RetroPie (I’d like to run Pegasus alone and configure it to run emulators directly).
Using Skyscraper to create metalists for pegasus and placing them in `$flatpakdir/org.pegasus_frontend.Pegasus/config/pegasus-frontend` did not change the result.

Thanks in advance!

**Comment by merwok** [comment]
Tagging the author of the flatpak build @mmatyas

**Comment by mmatyas** [comment]
Hm that's quite interesting, it seems as if the Qt libraries Pegasus uses got changed. Will look into it.

**Comment by mmatyas** [comment]
Weird, I've rebuilt it locally and there it works fine. I wonder what's up with that.

**Comment by bilelmoussaoui** [comment]
It might need a rebuild here on Flathub after the runtime update? You can trigger a new build from https://flathub.org/builds/#apps/org.pegasus_frontend.Pegasus

**Comment by mmatyas** [comment]
Thanks, rebuilding indeed seems to have fixed the issue. Just published the updated version, give it a try!

**Comment by merwok** [comment]
It starts now!  :sparkles: :rocket: :shipit: 
Thank your for the prompt action.
