### ISSUE TITLE
Update commit hash workflow not running anymore

### ISSUE THREAD

**Issue by j8r** [flathub/org.pegasus_frontend.Pegasus#12]
Unfortunately after two months GitHub automatically disable any GitHub Action cron.
They usually send a mail to reactivate it for another 2 months.

cc @mmatyas

**Comment by mmatyas** [comment]
I'm not technically the owner of the repo so I can't reactivate jobs :/

**Comment by j8r** [comment]
Even if you have the merge hability? You are not able to go to the `Actions` tab, then select the workflow and enable it again?

**Comment by mmatyas** [comment]
Oh you're right, there's indeed a button there, just not where I was expecting it. I've reenabled the workflow.
