### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by hfiguiere** [flathub/org.pegasus_frontend.Pegasus#13]
The build has been broken for 3 month:

https://buildbot.flathub.org/#/apps/org.pegasus_frontend.Pegasus

**Comment by j8r** [comment]
Thanks! Any way to be notified?

**Comment by mmatyas** [comment]
Should be fixed by https://github.com/mmatyas/pegasus-frontend/pull/1006

**Comment by hfiguiere** [comment]
that's why there are automatic builds on pull requests.

**Comment by j8r** [comment]
With flathubbot you mean?
We could use it here I guess, but for other bigger projects it has the opposite effect of creating too much PRs, which has then to be closed manually.

**Comment by mmatyas** [comment]
The last build seems to be successful, so closing the issue.
