### ISSUE TITLE
Is this actually possible to run as a Flatpak? Can it run external commands?

### ISSUE THREAD

**Issue by TiZ-HugLife** [flathub/org.pegasus_frontend.Pegasus#3]
Hi there. I'm currently using the static binary builds, but wouldn't mind switching over to this after the next tagged release as long as it actually works.

The whole thing is based around defining commands to run in your metadata files, and the commands may require system applications or other flatpaks. I know I make heavy use of convenience scripts in my current setup. So given that flatpak is usually meant to sandbox things, do such configurations even work this way?

**Comment by mmatyas** [comment]
Hi, well actually we're kind of trying to figure that out too -- see https://github.com/mmatyas/pegasus-frontend/issues/657. In theory, as long as Pegasus can access the programs you'd like to launch, thing should work fine (by default it only sees your home directory).

**Comment by TiZ-HugLife** [comment]
I would imagine that liberal use of [flatpak-spawn --host](https://www.mankier.com/1/flatpak-spawn) needs to be employed here. I guess the question would be, do we expect Pegasus to automatically flatpak-spawn --host on any command in metadata.txt, do we expect the user to configure that themselves, or do we want to add a metadata option?

**Comment by merwok** [comment]
I have found this other program that works with flatpak steam: https://github.com/flathub/com.valvesoftware.Steam.Utility.protontricks

**Comment by TiZ-HugLife** [comment]
That's not relevant. That is an extension to the Steam flatpak and is installed basically within the sandbox.

If you want Flatpak Pegasus to be able to look into the steam config directory, you need to request read access to `$HOME/.var/app/com.valvesotware.Steam`. If you want Flatpak Pegasus to be able to launch an app, you probably need `flatpak-spawn --host.`

**Comment by mmatyas** [comment]
If I remember correctly, this got fixed (Pegasus calls `flatpak-spawn`), so closing the issue.
