### ISSUE TITLE
Shutdown or reboot only exit Pegasus

### ISSUE THREAD

**Issue by j8r** [flathub/org.pegasus_frontend.Pegasus#8]
Confirming the shutdown or reboot through the menu only exits Pegasus, usually back to the main desktop, without triggering anything else.

This doesn't happen when compiling the project then using the produced binary as-is.

**Comment by mmatyas** [comment]
Interesting, is this a limitation of Flatpak, a permission issue, or something else, I wonder?

**Comment by j8r** [comment]
I think it's be due to sandbox permission lacking. Adding arguments like `--system-talk-name=org.freedesktop.GeoClue2` should fix it.

**Comment by j8r** [comment]
I think it's due to lacking sandbox permission. Adding arguments like `--system-talk-name=org.freedesktop.GeoClue2` should fix it.

**Comment by j8r** [comment]
No luck by adding `- --system-talk-name=org.freedesktop.login1` or `- --socket=system-bus`, so no idea.

**Comment by j8r** [comment]
For Kodi the login1 permission is enough: https://github.com/flathub/tv.kodi.Kodi/blob/master/tv.kodi.Kodi.yml

**Comment by j8r** [comment]
I've seen that the `dbus-send` binary is used, it could be the cause. It is not present in the flatpak package.

**Comment by j8r** [comment]
I found how to fix the issue :smile: .
The original source code has to be modified to use `flatpak-spawn --host dbus-send`.
